# Generated by Django 4.2.6 on 2023-11-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAL', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='ctiy',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
