# Generated by Django 4.2.6 on 2024-01-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(blank=True, max_length=80),
        ),
    ]
