# Generated by Django 3.2.14 on 2023-10-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(blank=True, max_length=20)),
                ('sku', models.CharField(blank=True, max_length=30)),
                ('sku_sn', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('price', models.IntegerField()),
                ('bullet_point', models.CharField(blank=True, max_length=3000)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
