# Generated by Django 3.2.22 on 2023-10-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JAL', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDescription',
        ),
    ]
