# Generated by Django 3.2.10 on 2022-11-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JAL', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsinInfo',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ProductDescription',
        ),
        migrations.DeleteModel(
            name='ProductInfo',
        ),
        migrations.DeleteModel(
            name='SalesStatus',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
