# Generated by Django 4.2.6 on 2024-01-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAL', '0002_alter_useraccount_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email_platform',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
