# Generated by Django 4.2.6 on 2023-11-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAL', '0002_useraccount_created_at_useraccount_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_at',
            field=models.DateTimeField(),
        ),
    ]
