# Generated by Django 4.2.6 on 2023-12-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAL', '0003_alter_coupon_end_at_alter_coupon_start_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promote_type', models.CharField(blank=True, max_length=20)),
                ('promote_code', models.CharField(blank=True, max_length=20)),
                ('promote_img', models.CharField(blank=True, max_length=500)),
                ('bullet_point_01', models.CharField(blank=True, max_length=500)),
                ('bullet_point_02', models.CharField(blank=True, max_length=500)),
                ('bullet_point_03', models.CharField(blank=True, max_length=500)),
                ('promote_url', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductDescription',
        ),
    ]
