# Generated by Django 3.2.22 on 2023-10-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAL', '0003_productdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
