# Generated by Django 3.2.14 on 2022-12-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAL', '0003_asininfo_cart_image_order_productdescription_productinfo_salesstatus_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
