# Generated by Django 3.2.22 on 2023-10-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAL', '0004_alter_productdescription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
