# Generated by Django 3.2.22 on 2023-10-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAL', '0004_productinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bullet_point',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
