# Generated by Django 4.2.6 on 2023-12-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JAL', '0005_promote_promote_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='type_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='promote',
            old_name='promote_channel',
            new_name='channel',
        ),
        migrations.RenameField(
            model_name='promote',
            old_name='promote_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='promote',
            old_name='promote_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='promote',
            old_name='promote_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='promote',
            old_name='promote_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='asin',
        ),
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='user_shipping',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='promote',
            name='status',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
